// Objective-C API for talking to github.com/mindsgn-studio/pocket-money-app/core Go package.
//   gobind -lang=objc github.com/mindsgn-studio/pocket-money-app/core
//
// File is generated by gobind. Do not edit.

#ifndef __Core_H__
#define __Core_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class CoreWalletCore;

@interface CoreWalletCore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)createEthereumWallet:(NSString* _Nullable)name error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getBalance:(NSString* _Nullable)network error:(NSError* _Nullable* _Nullable)error;
- (BOOL)init_:(NSString* _Nullable)dataDir password:(NSString* _Nullable)password masterKeyB64:(NSString* _Nullable)masterKeyB64 kdfSaltB64:(NSString* _Nullable)kdfSaltB64 error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)listAccounts:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)sendMoneyTo:(NSString* _Nullable)p0 p1:(NSString* _Nullable)p1 p2:(NSString* _Nullable)p2 error:(NSError* _Nullable* _Nullable)error;
@end

@interface Core : NSObject
+ (NSError* _Nullable) errNotInitialized;
+ (void) setErrNotInitialized:(NSError* _Nullable)v;

@end

FOUNDATION_EXPORT CoreWalletCore* _Nullable CoreNewWalletCore(void);

#endif
