// Objective-C API for talking to github.com/mindsgn-studio/pocket-money-app/core Go package.
//   gobind -lang=objc github.com/mindsgn-studio/pocket-money-app/core
//
// File is generated by gobind. Do not edit.

#ifndef __Core_H__
#define __Core_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class CoreAccountSummary;
@class CoreTransaction;
@class CoreTransactionMetadata;
@class CoreWalletCore;

@interface CoreAccountSummary : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletAddress;
@property (nonatomic) NSString* _Nonnull network;
@property (nonatomic) NSString* _Nonnull asset;
@property (nonatomic) NSString* _Nonnull balance;
@property (nonatomic) NSString* _Nonnull currency;
@end

@interface CoreTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) NSString* _Nonnull chain;
@property (nonatomic) NSString* _Nonnull token;
@property (nonatomic) NSString* _Nonnull amount;
// skipped field Transaction.Type with unsupported type: github.com/mindsgn-studio/pocket-money-app/core.TransactionType

// skipped field Transaction.State with unsupported type: github.com/mindsgn-studio/pocket-money-app/core.TransactionState

// skipped field Transaction.Metadata with unsupported type: github.com/mindsgn-studio/pocket-money-app/core.TransactionMetadata

@property (nonatomic) int64_t createdAt;
@property (nonatomic) int64_t updatedAt;
@end

@interface CoreTransactionMetadata : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull note;
@property (nonatomic) NSString* _Nonnull source;
@property (nonatomic) NSString* _Nonnull destination;
@property (nonatomic) NSString* _Nonnull providerID;
@end

@interface CoreWalletCore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)createEthereumWallet:(NSString* _Nullable)name error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)exportWalletBackup:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getAccountSummary:(NSString* _Nullable)network error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getBalance:(NSString* _Nullable)network error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)importWalletBackup:(NSString* _Nullable)payload passphrase:(NSString* _Nullable)passphrase error:(NSError* _Nullable* _Nullable)error;
- (BOOL)init_:(NSString* _Nullable)dataDir password:(NSString* _Nullable)password masterKeyB64:(NSString* _Nullable)masterKeyB64 kdfSaltB64:(NSString* _Nullable)kdfSaltB64 error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)listAccounts:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)listUsdcTransactions:(NSString* _Nullable)network limit:(long)limit offset:(long)offset error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)openOrCreateWallet:(NSString* _Nullable)name error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)sendMoneyTo:(NSString* _Nullable)network destination:(NSString* _Nullable)destination amount:(NSString* _Nullable)amount error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)sendUsdc:(NSString* _Nullable)network destination:(NSString* _Nullable)destination amount:(NSString* _Nullable)amount note:(NSString* _Nullable)note providerID:(NSString* _Nullable)providerID error:(NSError* _Nullable* _Nullable)error;
@end

// skipped const TransactionStateCompleted with unsupported type: github.com/mindsgn-studio/pocket-money-app/core.TransactionState

// skipped const TransactionStateFailed with unsupported type: github.com/mindsgn-studio/pocket-money-app/core.TransactionState

// skipped const TransactionStatePending with unsupported type: github.com/mindsgn-studio/pocket-money-app/core.TransactionState

// skipped const TransactionStateReversed with unsupported type: github.com/mindsgn-studio/pocket-money-app/core.TransactionState

// skipped const TransactionTypeCredit with unsupported type: github.com/mindsgn-studio/pocket-money-app/core.TransactionType

// skipped const TransactionTypeDebit with unsupported type: github.com/mindsgn-studio/pocket-money-app/core.TransactionType

// skipped const TransactionTypeTransfer with unsupported type: github.com/mindsgn-studio/pocket-money-app/core.TransactionType


@interface Core : NSObject
+ (NSError* _Nullable) errNotInitialized;
+ (void) setErrNotInitialized:(NSError* _Nullable)v;

@end

FOUNDATION_EXPORT CoreWalletCore* _Nullable CoreNewWalletCore(void);

#endif
